### ISSUE TITLE
Broken "Summary" View Links and "Move back to the previous context” button implementaion

### ISSUE THREAD

**Issue by EsQueEl-Fella** [trimble-oss/dba-dash#472] opened 2022-12-09 16:12 UTC
Version Used: 2.27.0

First Bug:
Step to reproduce:
1.	Start the DBADash GUI. We are now at root level "Summary" view.
2.	Chose one of the provided links like “Agent Jobs”. At this point we are moved to the chosen server node “Agent Jobs” view.
3.	Move along the navigation tree to the root level (DBA Dash) and click the “Checks” Item. We are now back to the "Summary" view.
4.	Choose one of the provided links like “Agent Jobs”. Nothing happens! Actually none of the links function anymore.

From here on the chaos starts! There are no visible errors / exceptions but basically nothing works as expected. Views aren't showing the correct data and in many cases they even don't react to any update / refresh. More or less, the easiest way to gain the control back, is to restart the GUI application. I believe this has somehow to do with the “Move back to the previous context” button functionality and implementation.

Second Bug:
Step to reproduce:
1.	Start the DBADash GUI. We are now at root "Summary" view.
2.	Choose the “Checks” of one server node in the navigation tree directly. We are now at "Summary" view of the server node.
3.	Choose any of the links there. Nothings works as expected. I even have managed to get various different Exceptions at this stage but I don’t know how to reproduce them as I have selected so many options and moved backward and forward so many times. 2 sample screenshot are attached.

I also relate this issue somehow to “Move back to the previous context” button functionality and implementation but I maybe wrong.

![grafik](https://user-images.githubusercontent.com/40255900/206741284-59aabd77-bea0-43d5-876e-0ad18070a331.png)
![grafik](https://user-images.githubusercontent.com/40255900/206744445-df0f0b7c-4503-4f54-ba33-0ea0ed4e929a.png)

**Comment by DavidWiseman** [comment] 2022-12-10 21:50
Thanks for reporting this.  I can reproduce this issue.  

Drill downs work at the root level or tag level if you are grouping by tag.  They are broken on the Checks node - either under the root node or an instance node. 

The bug occurs because it's looking down the tree to find the instance.  If you are at the "Checks" node in the tree it should first navigate up a level before looking down the tree.  

The weirdness occurs due to the tab load suppression that is enabled when the drill down is activated.  The drill-down needs to navigate to a particular node in the tree.  This would trigger the first tab to be loaded, but we might need to move to a different tab - making the first tab load redundant.  The suppression avoids the unnecessary tab load.

Unfortunately, if an instance isn't found, the tab load suppression isn't deactivated.  This causes the issue where the data isn't refreshing - requiring a restart of the app.  This makes it quite a nasty bug - I'll get it fixed in the next release.

**Comment by DavidWiseman** [comment] 2022-12-12 09:30
Issue fixed in 2.29.0

**Closed by DavidWiseman** 2022-12-12 09:30 UTC
Labels: DBA Dash GUI, defect, Completed
