### ISSUE TITLE
Error on instance hosted on an AWS RDS service

### ISSUE THREAD

**Issue by VincenzoMarchese** [trimble-oss/dba-dash#888] opened 2024-05-16 15:52 UTC
I have an issue monitoring a database instance hosted on an AWS RDS service. The DBA Dash user's has the following instance-level permissions: _processadmin_, _public_, _setupadmin_. On the master database, it's only a member of the _public_ role. On the msdb database, the user is a member of the roles: _public_, _SQLAgentUserRole_. I cannot add the user to the _db_datareader_ and _SQLAgentReaderRole_ roles. Can you suggest a solution? Thank you for the help.

Below is the error message (Source =  RunningJobs, Error context = Collect):
Microsoft.Data.SqlClient.SqlException (0x80131904): **The SELECT permission was denied on the object 'syssessions', database 'msdb', schema 'dbo'.**
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, SqlCommand command, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.SqlDataReader.TrySetMetaData(_SqlMetaDataSet metaData, Boolean moreInfo)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at Microsoft.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean isAsync, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String method)
   at Microsoft.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.SqlClient.SqlCommand.ExecuteReader()
   at DBADash.DBCollector.CollectRunningJobs() in D:\a\dba-dash\dba-dash\DBADash\DBCollector.cs:line 1031
   at DBADash.DBCollector.ExecuteCollection(CollectionType collectionType) in D:\a\dba-dash\dba-dash\DBADash\DBCollector.cs:line 1017
   at DBADash.DBCollector.<>c__DisplayClass69_0.<Collect>b__0(Context _) in D:\a\dba-dash\dba-dash\DBADash\DBCollector.cs:line 575
   at Polly.Policy.<>c__DisplayClass138_0.<Implementation>b__0(Context ctx, CancellationToken token)
   at Polly.Retry.RetryEngine.Implementation[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Action`4 onRetry, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider)
   at Polly.Retry.RetryPolicy.Implementation[TResult](Func`3 action, Context context, CancellationToken cancellationToken)
   at Polly.Policy.Implementation(Action`2 action, Context context, CancellationToken cancellationToken)
   at Polly.Policy.Execute(Action`2 action, Context context, CancellationToken cancellationToken)
   at DBADash.DBCollector.Collect(CollectionType collectionType) in D:\a\dba-dash\dba-dash\DBADash\DBCollector.cs:line 571
ClientConnectionId:55a40532-b741-4eb3-af39-6bbb336ead7e
Error Number:229,State:5,Class:14

**Comment by DavidWiseman** [comment] 2024-05-17 10:06
Hi,

As far as I can tell there doesn't seem to be a way to grant access on RDS.  

As a workaround the RunningJobs collection can be disabled by clicking the Schedule link associated with the instance on the Source tab of the config tool.  It isn't ideal to have to disable the collection manually - it should excluded by default if it's not supported.  This will be in the next release - possibly next week.

The job activity monitor in SSMS uses sp_help_job to get running jobs which works on RDS.  The problem is this doesn't provide any info on how long the job/job step has been running - so it can't be used as a replacement for the current query.

Thanks,

David

**Comment by VincenzoMarchese** [comment] 2024-05-17 10:41
Hi, and thanks for the response. I don't know if this will work the same, but it is possible to retrieve the duration of each job step through a script similar to the following. The column that contains the information is '**last_run_duration**'

USE msdb ;  
GO  
  
EXEC dbo.sp_help_job  
    @job_name = N'******************',  
    **@job_aspect = N'STEPS'** ;  
GO

EXEC dbo.sp_help_job  
    @job_name = N'******************',  
    **@job_aspect = N'ALL'** ;  
GO

**Comment by DavidWiseman** [comment] 2024-05-17 15:56
Hi, the last run time/date and duration are all for the previous job execution.  I'm going to fix the collection so we still get info on the running jobs but without the duration & start time.

**Comment by DavidWiseman** [comment] 2024-05-20 07:53
The fix is included in 3.5.1 🎉

**Comment by DavidWiseman** [comment] 2024-05-22 13:27
@VincenzoMarchese Hi, I think I might have spotted the mistake.  In the service config tool does the RDS instance have a checkbox in the No WMI column?  If it's checked, try unchecking it.  Save the config and restart the service.  Let me know if this fixes the problem.

The WMI collection will get disabled automatically for RDS.  The instance won't get flagged as RDS if No WMI has been set manually - I'll fix this bug.  If you can let me know what you find it will help confirm the issue.

Thanks.

**Comment by VincenzoMarchese** [comment] 2024-05-22 14:32
I confirm that in the service configuration tool, the RDS instance had the checkbox in the No WMI column selected. I unchecked it, saved the configuration, and restarted the service, and I no longer saw the error logged.

Thanks.

**Comment by DavidWiseman** [comment] 2024-07-03 12:35
Closing - fix is included in 3.5.2 onwards

**Closed by DavidWiseman** 2024-07-03 12:35 UTC
Labels: defect, DBA Dash Agent
