### ISSUE TITLE
Can not select columns in Running Queries

### ISSUE THREAD

**Issue by aachaemenes** [trimble-oss/dba-dash#1140] opened 2024-11-20 05:22 UTC
There is an issue with choosing columns to display in Running queries tab. You can not see witch items(columns) are selected

![running queries](https://github.com/user-attachments/assets/4780f113-6af1-47f3-89e9-729ca42220c4)

**Comment by DavidWiseman** [comment] 2024-11-20 08:14
This is related to #996, #938.  The checkbox won't be visible if the row height is too small.  Increasing the height manually is a workaround.

It's odd as this issue impacts some users and not others.  The default row height should be 29, but it's set to 24 in many places.  This still looks OK on my computer and the checkboxes display normally.  On your computer - I can see the height is too small - even the running queries grid in the background.  Maybe some graphics or font setting makes a difference, but either way, it's worth changing the height back to the default of 29.  I've done a bulk fix for this.

I'm not sure how they got set to 24 as it's unlikely I did this intentionally - probably a designer issue at some point.

**Comment by DavidWiseman** [comment] 2024-11-20 17:05
Fixed in 3.25 🎉

**Comment by tomaszwojcik12** [comment] 2024-11-23 20:30
Hi, the issue is still there even after update to 3.15. The workaround you mention (change row height size) works.
If I work on big external screen all is fine. If I work on 15" laptop screen, then I face mentioned issue. Additionally summary page looks weird then. Columns on bottom grid are too narrow.
![image](https://github.com/user-attachments/assets/6742d8e0-a876-410a-a9cd-ee5e79a523d3)

Same case for a few other tabs:
![image](https://github.com/user-attachments/assets/db7aa270-47b5-454b-a637-e0ddec4c2339)

If it matters, I use DBA Dash on RDP session.

**Comment by DavidWiseman** [comment] 2024-11-25 09:53
I'm not able to reproduce this issue.  It works OK for me on a 15" laptop screen via RDP.  The checkboxes are still visible and the summary columns are sized appropriately with horizontal scrollbars on the smaller screen when needed.
What is the resolution of the laptop screen and scaling used?  I've tried messing about with resolution and scaling but I still can't reproduce the issue.
What RDP client is used?  What version of Windows?

**Comment by FuriousDBA** [comment] 2024-11-25 11:39
Hi, thanks for response.
I'm on Windows 11, using Windows Remote Desktop Connection
![image](https://github.com/user-attachments/assets/dd29a1ee-8e89-4c90-a8ec-b60146b11171)
![image](https://github.com/user-attachments/assets/b589a88b-f0ef-4196-8b05-e52e1729efed)

The remote server is Windows Server 2022

**Comment by DavidWiseman** [comment] 2024-11-25 12:16
Thanks - I can replicate this.  The scale at 250% is causing the issue and it doesn't need to be a RDP session.  Setting the resolution lower and reducing the scale would fix the issue but won't make best use of the high PPI display.  
I'll investigate how I can fix the issue - at least I can reproduce it now.

**Comment by DavidWiseman** [comment] 2024-11-25 22:48
This is a better workaround:

* Right-click DBADash.exe
* Click change high DPI settings on Compatibility tab
* Check the Override high DPI scaling behaviour checkbox.
* Select System (Enhanced)

![image](https://github.com/user-attachments/assets/fea64f12-1519-493f-9303-fdbae29de06b)

It's not a perfect solution.  Some text might not be as crisp as it should be - which probably won't be that noticeable on a small screen.

**Comment by FuriousDBA** [comment] 2024-11-26 12:00
Workaround works, thanks a lot

**Comment by DavidWiseman** [comment] 2024-12-06 08:02
Hi, I've got a fix #1151 to improve support for high DPI displays where scaling is set to 250% etc.  It will be included in the next release, but if you want to try it out before then, you can use the [custom build here](https://github.com/DavidWiseman/dba-dash/releases/tag/3.15.0).

It should look better than with the workaround above.  If you have multiple displays with different scaling, this situation isn't handled perfectly and the app is optimized for the primary display.  It will still scale properly for the secondary display but might not look as crisp as it should be.  There is a Per-Monitor V2 scaling option I can use to address this but various controls in WinForms don't work well with this - they look crisp, but are not being sized correctly.

**Comment by FuriousDBA** [comment] 2024-12-06 13:20
Hi @DavidWiseman 
I checked the custom build. It works fine on my laptop screen.
Thanks a lot for your support!
BTW: DBA_Dash is great :)

**Comment by DavidWiseman** [comment] 2024-12-06 13:25
Thanks for the feedback! ♥️

**Comment by DavidWiseman** [comment] 2024-12-11 09:22
Fix included in 3.16 🚀

**Closed by DavidWiseman** 2024-12-11 09:22 UTC
Labels: DBA Dash GUI, defect, Completed
