### ISSUE TITLE
Data is Null. This method or property cannot be called on Null values.

### ISSUE THREAD

**Issue by chucklor** [trimble-oss/dba-dash#879] opened 2024-05-10 14:10 UTC
I'm setting up the DBA Dash Service Config and I'm getting this error all the time. It will not let me deploy/update database.
![image](https://github.com/trimble-oss/dba-dash/assets/20845188/6938833b-b691-496f-8fd5-892526401c4d)

**Comment by DavidWiseman** [comment] 2024-05-10 20:31
Hi, did the database get created on the destination SQL instance?  If the database exists, run this query and let me know what it returns:

```
IF EXISTS(
	SELECT * FROM sys.extended_properties
	WHERE major_id=OBJECT_ID('DBVersionHistory')
	AND name = 'AppID'
	AND value='74F9FD8A-DF22-4355-9A7A-6E1F4AE712B9'
)
BEGIN 
	SELECT TOP(1) Version
	FROM dbo.DBVersionHistory
	ORDER BY DeployDate DESC
END
ELSE IF NOT EXISTS(SELECT * 
			FROM sys.objects
			WHERE type NOT IN('S','IT','SQ')          
            )
        AND DB_ID()>4
BEGIN
	SELECT '0.0.0.0' AS Version
END
ELSE
BEGIN 
	RAISERROR('Invalid database',11,1)
END
```
Note: This is a script that is used as a version check.  It helps ensure that the dacpac is deployed either to an empty database or the correct repository database.  I don't think this is the issue but it might help troubleshoot.

Also, can you run this query on your destination connection.  Please use the same account as used for the DB deployment.

```
SELECT SERVERPROPERTY('EngineEdition'),SERVERPROPERTY('ProductVersion'),DB_NAME(),@@SERVERNAME,SERVERPROPERTY('ComputerNamePhysicalNetBIOS')
```

I don't need to know the servername - I'm wondering if any of these might return null for some reason.  The version might be useful to know.  Also, can you let me know which version of DBA Dash you are using?

If the database has been created, you might want to try deleting it and allow the service to create it on startup.

**Comment by DavidWiseman** [comment] 2024-05-11 08:00
Hi,  I might have figured this out.  I can reproduce the error by getting `@@SERVERNAME` to return a NULL value.  You can check if this returns NULL for your SQL instance by running:

`SELECT @@SERVERNAME`

or
`SELECT* FROM sys.servers WHERE server_id=0`

`@@SERVERNAME` should be returning the name of your SQL instance rather than NULL and the second query should return 1 row.  

🔧 If you validate that this is the same problem for your SQL instance, you can fix it by running [sp_addserver](https://learn.microsoft.com/en-us/sql/relational-databases/system-stored-procedures/sp-addserver-transact-sql?view=sql-server-ver16) and restarting the instance:

`sp_addserver '<name_of_your_instance>', 'local'`

---
I was able to reproduce this issue in my lab environment by running this command and restarting the SQL instance.

```
---⚠️For lab environment only
sp_dropserver @@SERVERNAME
```

**Comment by DavidWiseman** [comment] 2024-05-11 08:30
I'm going to improve the error message to make it clear what the problem is:

![image](https://github.com/trimble-oss/dba-dash/assets/33157668/4cb4b4f7-1c06-4fbc-b545-f3354e9d3c35)

I might be able to work around the NULL servername but I don't think the issue is very common.

**Comment by DavidWiseman** [comment] 2024-05-13 11:03
This is fixed in 3.5.

**Closed by DavidWiseman** 2024-05-13 11:03 UTC

**Comment by chucklor** [comment] 2024-05-14 13:35
Thank you so much! I think I got it work. However, I'm curious what this warning means.
![image](https://github.com/trimble-oss/dba-dash/assets/20845188/fee37915-d104-4e2a-a93d-e2e9ddb33274)

**Comment by DavidWiseman** [comment] 2024-05-14 15:02
@chucklor The warning is there because the function `@@SERVERNAME` returned NULL.  Usually this returns the name of the SQL instance.  e.g. DB1
If you run `SELECT @@SERVERNAME` on the SQL instance you should see the problem.

DBA Dash can now handle the NULL value but it will display a warning.  You can ignore it and everything should be OK but it's possible that you will run into problems with other scripts that might expect this function to return the name of the SQL instance.

I'm guessing sp_dropserver was called on this server at some point.  You might need to do this if you rename the server, but you would usually call sp_addserver to replace with the new servername. 

To get `@@SERVERNAME` to return the name of the server you will need to run:

`sp_addserver '<name_of_your_instance>', 'local'`

The new name will need an instance restart to pick up.

**Comment by DavidWiseman** [comment] 2024-05-14 15:05
sp_dropserver is also used to remove linked servers - so you might have removed it by accident when removing the linked servers.

**Comment by chucklor** [comment] 2024-05-14 15:11
Again, thank you for the help. Since I've installed version 3.5, for some reason I'm getting this popup and no longer able to connect to my instance.
![image](https://github.com/trimble-oss/dba-dash/assets/20845188/41e4d27d-6bd1-4d1e-b29f-398cb65bca67)
I clicked OK on the above popup and then I get this one.
![image](https://github.com/trimble-oss/dba-dash/assets/20845188/3acb6d71-6633-47a3-9e42-8d7783b775a8)

**Comment by DavidWiseman** [comment] 2024-05-14 15:27
Hi,

Version 0.0 probably indicates an empty repository database.  When the service runs it should deploy create/deploy the database.  Did you create the repository database manually?  
There is a Logs folder that you can check.  If the service is started it's possible that it's having issue deploying the dacpac - the service should have database owner access to the repository database.

There ia a [quick start](https://dbadash.com/docs/setup/quick-start/) guide that might be useful.

Hope this helps,

David

**Comment by chucklor** [comment] 2024-05-14 17:18
My question now is, how do I add additional SQL Server instances to the DBA Dash? I have followed the quick start you posted above and manually deployed the DBADashDB catalog to DB14. I do see that this DBADashDB database is created on DB14. However, I am not sure if the DBADashService is also needed to run on DB14 or not. Currently this DBADashService account service is not running on DB14.
![image](https://github.com/trimble-oss/dba-dash/assets/20845188/302c3ad4-746d-4f7d-921a-81b5c75d4f19)

**Comment by chucklor** [comment] 2024-05-14 19:36
@DavidWiseman , thank you so much for the help and your patience. You're right. The issue seems to be the permission of the account I used to connect to DB14. I think I got it figured out now. Both instances appeared on the DBA Dash now.

**Comment by DavidWiseman** [comment] 2024-05-14 19:40
That's great - glad you got it sorted.  Hope you find it useful! 😊
