### ISSUE TITLE
TableSize (and perhaps other reports) collection collation issue

### ISSUE THREAD

**Issue by TDaphneB** [trimble-oss/dba-dash#886] opened 2024-05-15 19:51 UTC
Hi,

We are currently running DBA Dash version 3.4.2.0 and just turned on the TableSize report. There is an issue in actually collecting the data. Unfortunately our set up is a little strange for this set of databases in that their collation does differ from the server collation. 
- Server: SQL_Latin1_General_CP1_CI_AS
- Database: Latin1_General_CI_AS

When running the collector for the table size report then we get the following error:
```
Microsoft.Data.SqlClient.SqlException (0x80131904): Cannot resolve the collation conflict between "SQL_Latin1_General_CP1_CI_AS" and "Latin1_General_CI_AS" in the equal to operation.
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, SqlCommand command, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at Microsoft.Data.SqlClient.SqlDataReader.get_MetaData()
   at Microsoft.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean isAsync, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String method)
   at Microsoft.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.FillInternal(DataSet dataset, DataTable[] datatables, Int32 startRecord, Int32 maxRecords, String srcTable, IDbCommand command, CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.Fill(DataTable[] dataTables, Int32 startRecord, Int32 maxRecords, IDbCommand command, CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.Fill(DataTable dataTable)
   at DBADash.DBCollector.GetDT(String tableName, String SQL, Int32 commandTimeout, SqlParameter[] param) in D:\a\dba-dash\dba-dash\DBADash\DBCollector.cs:line 1250
   at DBADash.DBCollector.AddDT(String tableName, String sql, Int32 commandTimeout, SqlParameter[] param) in D:\a\dba-dash\dba-dash\DBADash\DBCollector.cs:line 1259
   at DBADash.DBCollector.ExecuteCollection(CollectionType collectionType) in D:\a\dba-dash\dba-dash\DBADash\DBCollector.cs:line 1008
   at DBADash.DBCollector.<>c__DisplayClass66_0.<Collect>b__0(Context _) in D:\a\dba-dash\dba-dash\DBADash\DBCollector.cs:line 562
   at Polly.Policy.<>c__DisplayClass138_0.<Implementation>b__0(Context ctx, CancellationToken token)
   at Polly.Retry.RetryEngine.Implementation[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Action`4 onRetry, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider)
   at Polly.Retry.RetryPolicy.Implementation[TResult](Func`3 action, Context context, CancellationToken cancellationToken)
   at Polly.Policy.Implementation(Action`2 action, Context context, CancellationToken cancellationToken)
   at Polly.Policy.Execute(Action`2 action, Context context, CancellationToken cancellationToken)
   at DBADash.DBCollector.Collect(CollectionType collectionType) in D:\a\dba-dash\dba-dash\DBADash\DBCollector.cs:line 558
ClientConnectionId:8196a205-465b-4717-8678-65aff0d8dc97
Error Number:468,State:9,Class:16
ClientConnectionId before routing:7ba47f06-a97d-4875-ae48-cd566d08df75
Routing Destination:edd8faed3d85.tr10165.australiaeast1-a.worker.database.windows.net,11042
```

I was looking for where this would be coming from and believe it is on the comparison of the schema_name and object_name in the [SQLTableSize.sql](https://github.com/trimble-oss/dba-dash/blob/main/DBADash/SQL/SQLTableSize.sql) file. 

Would there be a very large performance impact of adding something like `COLLATE DATABASE_DEFAULT` to this? 🤔 

I'm happy to make such a change if that is beneficial to the project as a whole. But if not we can go the custom report route or alter specifically on our version instead for this odd collation case.

**Comment by DavidWiseman** [comment] 2024-05-16 08:14
Hi, thanks for reporting this issue.  I don't seem to be able to reproduce this in my lab environment just by having databases where the collation doesn't match the server collation.  Can you run the [TableSize](https://raw.githubusercontent.com/trimble-oss/dba-dash/main/DBADash/SQL/SQLTableSize.sql) collection manually on the instance?  You will need to uncomment the top part of the script where the app usually supplies the parameters.  Once you can reproduce the problem if you are able to identify a fix you could submit a pull request for me to review.  Or you can post back here with details of the changes you made to get it working.  
Also, what does this return on your SQL instance?  Run it from the database that DBA Dash connects to (usually master, but you might have specified a different DB)
```
SELECT CONVERT (varchar, SERVERPROPERTY('collation')) AS 'Server Collation'
SELECT name, collation_name FROM sys.databases WHERE name IN('master','tempdb',DB_NAME());
```

Thanks

**Comment by TDaphneB** [comment] 2024-05-16 21:37
Hi David,

I cannot get access to the tempdb collation (we are running on Azure SQL) but here is the result for the server, master and troublesome DB. I would assume that tempdb is using the server collation.
![image](https://github.com/trimble-oss/dba-dash/assets/2857220/7e1cd8bf-7595-4398-955c-89fb2f1be1aa)

DBA Dash itself is on another server as follows:
![image](https://github.com/trimble-oss/dba-dash/assets/2857220/94ac6c91-76b4-465b-8798-da63efa82c04)

Executing the TableSize script manually gives the collation conflict error on the following two lines:
![image](https://github.com/trimble-oss/dba-dash/assets/2857220/c20b84c6-8318-4889-9eff-12a972a4499f)

I have created a PR here for you to have a look: #890

**Comment by DavidWiseman** [comment] 2024-05-17 07:52
Hi,  thank you for submitting a PR.  It's merged and will be included in the next release.  🎉

I suspected that was where the issue was occurring but I was unable to reproduce it on a regular SQL instance.  I can reproduce it easily on Azure DB though which is interesting.  I was able to test your fix and it's working great.

Thanks 🙏

**Comment by DavidWiseman** [comment] 2024-05-20 07:24
Your fix is included in the latest release 🎉  Thanks for the contribution! 😊

**Closed by DavidWiseman** 2024-05-20 07:24 UTC
Labels: Completed
