### ISSUE TITLE
Performance Counter 'Buffer cache hit ratio' not visible in Metrics tab

### ISSUE THREAD

**Issue by petervd** [trimble-oss/dba-dash#255] opened 2022-07-13 13:21 UTC
The Performance Counter 'Buffer cache hit ratio' is not showing in Metrics tab.

It is specified in PerformanceCounters.xml
`
  <Counter object_name="Buffer Manager" counter_name="Buffer cache hit ratio" instance_name="" />
  <Counter object_name="Buffer Manager" counter_name="Buffer cache hit ratio base" instance_name="" />
  <Counter object_name="Buffer Manager" counter_name="Lazy writes/sec" instance_name="" />
  <Counter object_name="Buffer Manager" counter_name="Checkpoint pages/sec" instance_name="" />
  <Counter object_name="Buffer Manager" counter_name="Free list stalls/sec" instance_name="" />
  <Counter object_name="Buffer Manager" counter_name="Page life expectancy" instance_name="" />
  <Counter object_name="Buffer Manager" counter_name="Page reads/sec" />
  <Counter object_name="Buffer Manager" counter_name="Page writes/sec" />
`
There is a record in table CounterMapping

object_name	counter_name	base_counter_name
SQLServer:Buffer Manager	Buffer cache hit ratio	Buffer cache hit ratio base

The agent is already running for weeks continuously collecting data.

The other 6 Buffer Manager counters are visible

Am I missing a configuration setting that I need to activate? Or is something else missing.

**Comment by DavidWiseman** [comment] 2022-07-13 21:41
Hi,

This is a bug!  Thank you for reporting it.  I've found the problem and I should have a fix available for it soon.

There are a couple of issues with the handling of this specific counter type (537003264  - PERF_LARGE_RAW_FRACTION).  

Thanks,

David

Note: The Buffer Cache Hit Ratio counter was quite popular for detecting memory pressure and many monitoring tools include this counter.  The counter probably isn't very useful though. See[ here](https://www.red-gate.com/simple-talk/databases/sql-server/database-administration-sql-server/great-sql-server-debates-buffer-cache-hit-ratio/).

**Comment by petervd** [comment] 2022-07-14 04:36
Hi David,

Thank you for your reply.

I really enjoy using the DbaDash tool and find it very useful in monitoring our SQL Servers. I am just starting to try-out what is possible beyond the out-the-box configuration. This is how I bumped into this metric issue.

Many thanks,
Peter

**Comment by DavidWiseman** [comment] 2022-07-15 07:13
The issue is fixed in the 2.19.1 release just published. I'm glad you are finding the tool useful!  😊

Note: If you want to customize the counters collected, it's best to create a copy of PerformanceCounters.xml called PerformanceCountersCustom.xml.  This is just because PerformanceCounters.xml will get overwritten when you upgrade to a new version.  The default one is ignored when the custom one is available.  [More info here](https://github.com/trimble-oss/dba-dash/blob/main/Docs/OSPerformanceCounters.md).

**Closed by DavidWiseman** 2022-07-15 07:13 UTC
Labels: defect, Completed, Repository DB

**Comment by petervd** [comment] 2022-07-19 18:08
I installed version 2.19.1 and the counter is now showing in the metrics screen.

Many thanks.
