### ISSUE TITLE
Mouse Pointer

### ISSUE THREAD

**Issue by jacobgexigo** [trimble-oss/dba-dash#80] opened 2022-03-17 00:41 UTC
The mouse pointer turns into a vertical line with an arrow to each side when in the application.  This is only place where this has ever happened.  It makes clicking on things in the GUI difficult.  I have installed this on two different machines and it does the same thing.  This is using the most recent build but it did it on one back as well.

![image](https://user-images.githubusercontent.com/29784949/158714018-91540e97-de2a-46cf-a4b4-06e4ae8e6e31.png)

**Comment by DavidWiseman** [comment] 2022-03-17 07:39
Hi,  this occurs for me also but I wasn't sure if it was a problem with my big mouse cursor setup - maybe just affecting me.  It didn't bother me too much so I never looked at it.  I've had a quick look now though and I've worked out what the problem is.  It's an easy fix so this will make it in the next release. 😊

**Comment by DavidWiseman** [comment] 2022-03-17 16:32
The mouse pointer issue is fixed now in the latest release.  Thank you for reporting the issue.

**Closed by DavidWiseman** 2022-03-17 16:32 UTC
Labels: client
