### ISSUE TITLE
System.NullReferenceException: Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by EsQueEl-Fella** [trimble-oss/dba-dash#313] opened 2022-09-22 06:10 UTC
Here yet another small issue I recently discovered:
![null_reference](https://user-images.githubusercontent.com/40255900/191671078-e2468523-b787-43d0-88ad-83b9bb8043fc.png)

************** Ausnahmetext **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at DBADashGUI.Performance.CPU.TsUp_Click(Object sender, EventArgs e) in D:\a\dba-dash\dba-dash\DBADashGUI\Performance\CPU.cs:line 239
   at System.Windows.Forms.ToolStripButton.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)

**Comment by DavidWiseman** [comment] 2022-09-22 06:54
Thank you for reporting this issue - I will investigate.

**Comment by DavidWiseman** [comment] 2022-09-22 08:19
Thank you.  I don't get this error but I'll see if I can figure it out.

**Comment by DavidWiseman** [comment] 2022-09-22 10:49
I've realized what the issue is - this issue occurs on the "Performance" tab.  You can create your own dashboards on the Metrics tab where this feature will work.  It should be disabled on the "Performance" tab.

**Comment by DavidWiseman** [comment] 2022-09-22 13:12
This is fixed in 2.22.4 🎉

**Closed** 2022-09-22 13:12 UTC
Labels: DBA Dash GUI, defect, Completed
