### ISSUE TITLE
CPU Information not showing when server is busy

### ISSUE THREAD

**Issue by aachaemenes** [trimble-oss/dba-dash#1144] opened 2024-11-20 21:15 UTC
DBADASH wont collect CPU data when cpu is pegged or is close to be pegged. It shows empty.

**Comment by DavidWiseman** [comment] 2024-11-21 08:28
DBA Dash collects CPU utilization from ring buffer using [this query](https://github.com/trimble-oss/dba-dash/tree/main/DBADash/SQL).  Check what data you have in the ring buffer for the missing time period.  

One possibility is the CPU is reporting over 100% in the ring buffer.  DBA Dash will filter these out on import.  I've had one user report that this is an issue but I'm not clear on the root cause of this or how it should be fixed.  It seems to occur only on bare metal instances and maybe certain CPU configurations.  

Let me know if you are getting values over 100.  If you are what the CPU configuration (physical CPUs, core counts, NUMA nodes etc) looks like on your system and if it's bare metal or hypervisor.  It could be worth a support ticket with MS for an official explanation - I'd like to, but I'm not able to reproduce this issue.

**Closed** 2024-12-11 09:22 UTC
Labels: Completed
