### ISSUE TITLE
DBA dash having issues with schema import when stored procedure is encrypted

### ISSUE THREAD

**Issue by BrubiSQL** [trimble-oss/dba-dash#117] opened 2022-04-04 11:36 UTC
Hi,
As written in the title, I have stumbled across an issue with DBA dash data ingestion when there is encrypted stored procedure.
DBA dash doesn't pull schema information.
Eg, it doesn't pull data regarding tables, and it doesn't pull data from that specific stored procedure.
It would be good, if DBA Dash would skip encrypted SP, and just continue without it, maybe just mark it as encrypted and continue with data ingestion.
 
 
**ERROR:**
2022-04-04 13:03:50.999 +02:00 [INF] DB Snapshot DBAdash_testDB from instance RANDOM_SERVER_NAME <8>
2022-04-04 13:03:51.067 +02:00 [INF] Schema snapshot DBAdash_testDB: Aggregate completed in 3.9 ms <8>
2022-04-04 13:03:51.076 +02:00 [INF] Schema snapshot DBAdash_testDB: Assembly completed in 9.6 ms <8>
2022-04-04 13:03:51.080 +02:00 [INF] Schema snapshot DBAdash_testDB: UserDefinedType completed in 3.3 ms <8>
2022-04-04 13:03:51.083 +02:00 [INF] Schema snapshot DBAdash_testDB: XMLSchema completed in 3.6 ms <8>
2022-04-04 13:03:51.108 +02:00 [INF] Schema snapshot DBAdash_testDB: Schema completed in 25.1 ms <8>
2022-04-04 13:03:51.368 +02:00 [INF] Schema snapshot DBAdash_testDB: Tables completed in 259.5 ms <8>
2022-04-04 13:03:51.748 +02:00 [WRN] Schema snapshot DBAdash_testDB: StoredProcedures abandoned in 380.0 ms <8>
2022-04-04 13:03:51.748 +02:00 [WRN] Schema snapshot DBAdash_testDB abandoned in 749.0 ms <8>
2022-04-04 13:03:51.749 +02:00 [ERR] Error creating schema snapshot DBAdash_testDB <8>
Microsoft.SqlServer.Management.Smo.PropertyCannotBeRetrievedException: Property TextHeader is not available for StoredProcedure '[dbo].[WITH_ENCRYPTION]'. This property may not exist for this object, or may not be retrievable due to insufficient access rights. The text is encrypted.
   at Microsoft.SqlServer.Management.Smo.ScriptNameObjectBase.GetTextProperty(String requestingProperty, ScriptingPreferences sp, Boolean bThrowIfCreating)
   at Microsoft.SqlServer.Management.Smo.ScriptNameObjectBase.GetTextHeader(ScriptHeaderType scriptHeaderType)
   at DBADash.SchemaSnapshotDB.addSPs(Database db, DataTable dtSchema) in X:\a\dba-dash\dba-dash\DBADash\SchemaSnapshotDB.cs:line 1025
   at DBADash.SchemaSnapshotDB.SnapshotDB(String DBName) in X:\a\dba-dash\dba-dash\DBADash\SchemaSnapshotDB.cs:line 445
   at DBADashService.SchemaSnapshotJob.Execute(IJobExecutionContext context) in X:\a\dba-dash\dba-dash\DBADashService\SchemaSnapshotJob.cs:line 62
 
 
 
 
Data ingestion can be tested with this fictive database:
 
```
CREATE DATABASE [DBAdash_testDB]
GO
USE [DBAdash_testDB]
GO
CREATE TABLE [dbo].[Table1](
                [table1] [nchar](10) NULL,
                [table2] [nchar](10) NULL,
                [table3] [nchar](10) NULL,
                [table4] [nchar](10) NULL
) ON [PRIMARY]
GO
CREATE TABLE [dbo].[Table2](
                [table1] [nchar](10) NULL,
                [table2] [nchar](10) NULL,
                [table3] [nchar](10) NULL,
                [table4] [nchar](10) NULL
) ON [PRIMARY]
GO
CREATE TABLE [dbo].[Table3](
                [table1] [nchar](10) NULL,
                [table2] [nchar](10) NULL,
                [table3] [nchar](10) NULL,
                [table4] [nchar](10) NULL
) ON [PRIMARY]
GO
CREATE PROCEDURE [dbo].[WITH_ENCRYPTION]
WITH ENCRYPTION
AS
BEGIN
                SELECT * FROM sys.databases
END
GO
```

**Comment by DavidWiseman** [comment] 2022-04-04 19:39
Hi,

I agree - it would be best just to skip the encrypted stored procs and allow the snapshot to be created.  I don't think this will be difficult to fix - I'll take a look at this.  Thank you for including the reproduction.

The error handling for snapshots is done at a higher level as generally, it's better for the whole snapshot to fail rather than having a partial snapshot created due to some connectivity issue.  In this case, it would always error.  Definitely makes sense to catch this error and continue - or detect if it's encrypted first and skip.

Thanks,

David

**Comment by DavidWiseman** [comment] 2022-04-07 15:26
Additional object types to consider:
Functions, DDL Triggers, Triggers & Views

**Comment by DavidWiseman** [comment] 2022-04-07 18:51
Fix to be included in the next release

**Comment by DavidWiseman** [comment] 2022-04-08 06:31
Issue fixed in the latest release

**Closed by DavidWiseman** 2022-04-08 06:31 UTC
Labels: agent, Completed

**Comment by BrubiSQL** [comment] 2022-04-08 07:33
Thank you for your effort, and for your quick fix.
I have tested this, and it works just fine.

**Comment by DavidWiseman** [comment] 2022-04-08 07:36
Great!  Thank you for letting me know.

**Comment by petrk666** [comment] 2025-09-05 11:33
Hello,

currently DBADash correctly skips encrypted stored procedures during schema snapshots, but encrypted views, functions, and triggers still cause the snapshot to fail.

Could you please extend the same encrypted object handling to views, functions, and triggers, so that snapshots continue and a placeholder is inserted in the definition field (-- ENCRYPTED OBJECT (definition not accessible) --)?

Thank you!
