### ISSUE TITLE
Request for a "multi acknowledge" mechanism for Agent failed jobs and a more detailed representation of Job data

### ISSUE THREAD

**Issue by EsQueEl-Fella** [trimble-oss/dba-dash#700] opened 2023-09-18 15:47 UTC
Hi,
this is a feature request. DBADash version used: 2.46.0.0

Referring to the image attached, one can see [nr. 1] Agent jobs on many instances are being shown with warning (which by the way is a very useful feature). Now if the user wants to know which Job(s) did end up with Warning (or Failure), he/she needs to click and review the status for EACH single instance! This, in many cases given high number of installations/instances, is really time consuming and involves many steps, lots of clicks and each click means a travel to the DBADash DB and transfer data etc.

My suggestion/request, please provide
 - a mechanism to list all the failed "**job names**" in an additional column in the grid [nr. 2]. This can't be hard to implement because if you know the instance name and a failed job on that instance, then you already know the job name. If more jobs on the same instance have failed, can't be a problem to show them in the list either. I would also set the default sorting on the instance column which help one to see all the failed jobs for an instance groupwise.
 - a "**multi acknowledge**" ability. This is probably a bit harder to implement. I can think of using a checkbox for every single failed job in a new grid column [nr. 3] which can be selected by the user and a button "**Acknowledge All**". Or maybe something you prefer or find better but definitely a "**multi acknowledge**" ability. 

The feature as currently provided, is really costing me a lot of time as I MUST review EACH single failed job on EACH Instance. Sometime a simple network failure would cause one scheduled job fails on ALL the instances (and yes I know this shouldn’t happen, but we live on earth and not Utopia :D). Never-the-less I have to do the manual one million clicks to verify if everything else is fine! I hope you get my point and why a “**multi acknowledge**” mechanism is that important and valuable for daily tasks.

![grafik](https://github.com/trimble-oss/dba-dash/assets/40255900/c55f3340-42b1-4594-b02a-e6940d31218b)

**Comment by EsQueEl-Fella** [comment] 2023-09-18 16:05
I just discovered selecting the "**Agent Jobs**" link will provide the view with details I was asking for! 

So practically you have already done the job. You probably just need to show the same information (or a subset of that) in the list when one select the numbers in the "**Instance Count Warning**" / "**Instance count Critical**".

I can also live with the "**multi acknowledge**" mechanism provided. It is still lots of clicks but at least they are all in one place. 

![grafik](https://github.com/trimble-oss/dba-dash/assets/40255900/7bdd522a-d79d-4607-baa5-808b69bc3f25)

**Comment by DavidWiseman** [comment] 2023-09-18 17:27
I think this is already provided by the "Agent Jobs" link which will show all the jobs with Critical, Warning or Acknowledged status at root level.  The status filter can be adjusted easily from there if you just want to see jobs with Critical status.  The current behavior of the count links allows you to see a list of impacted servers which can also be useful - though I can also see the argument that it would be useful to drill down and apply the status filter.  

I might consider adding an option to multi-acknowledge job failures.  It's an option that probably needs to come with a warning though.  If you have job failures I would recommend investigating the root cause and fixing it so that the job doesn't fail in the future.  It can make sense to add retry logic to jobs - so the job doesn't actually go into a failed state if it hits a rare problem like a deadlock.

Thanks.

**Comment by DavidWiseman** [comment] 2023-09-21 15:15
Actually there is already a way to acknowledge all the job failures.  

![image](https://github.com/trimble-oss/dba-dash/assets/33157668/6fa7cfb5-0313-4b74-b56d-37f9aa891f45)

**Comment by DavidWiseman** [comment] 2023-09-22 07:46
Closing as feature already exists.  The acknowledge mechanism is also improved in 2.47 - sort order and column layout are now maintained when you acknowledge a job failure.

**Closed by DavidWiseman** 2023-09-22 07:46 UTC
