### ISSUE TITLE
Feature Request: Please change the behavior of the popup Tooltip window

### ISSUE THREAD

**Issue by EsQueEl-Fella** [trimble-oss/dba-dash#761] opened 2023-11-14 09:15 UTC
Hi,

This is a simple feature request.
Version used: 2.49.1.0

Please change the behavior and the amount of the text shown in the popup **Tooltip** window. See image. This feature, as it is now, is causing a lot of trouble. Loading huge texts costs time and performance and there are lot of times they even cause a total application freeze and I have to restart the GUI through Task manager ! Sometimes the tooltip window even covers all my Monitor and then the application freeze and I am wondering what is the point of the feature. I can't copy the text inside (I would use the Code Viewer for that), I can't read the text because it isn’t readable and it also wastes time and resources !

BTW, The point here isn't the content and the SQL commands and how they should be written to be performant and so on. I don't write these command and I also don't know what is inside a head of time until I hover over a link and boom, DBADash freeze ! and I have to restart it the hard way. This is really problematic. 

![grafik](https://github.com/trimble-oss/dba-dash/assets/40255900/5a5ef2e0-f5cd-4050-b523-9e533dcab756)

**Comment by DavidWiseman** [comment] 2023-11-14 22:03
I haven't experienced this problem. Do you know how many bytes of text it is?

**Comment by EsQueEl-Fella** [comment] 2023-11-15 10:44
No I have no idea. 

My main objective here is: no matter what, information in the tooltip, the way it is presented, isn’t useful and it comes even with some draw backs. Not all the queries passed around are one-liners :D

1. The information loaded into tooltip, the way it is presented, isn't readable. 
2. Very often the content which is carrying some formatting rules (Like TABs, Line Breaks or Whitespaces etc.) produce really odd visual output which even spans over 2 monitor horizontally or unreadable Window frame growth vertically !
3. One can't copy the content or use the information in any other way (Except visually).
4. The time the tooltip stays visible is really short. I measured, it is ONLY 5 seconds! How the user manage to read a book in such a short time, is puzzling me :D
5. It is simply too much content for a tooltip. Just look at the sample I posted as image which also was a PART of the whole text and not all!
6. In some occasions where there is too much content, it even causes an application freeze which ends up killing the process using task manager and restart the application. This process is really annoying and very time consuming. The user should use the application and not invest his/her time to find a workaround to the problems caused by the application. I will try to catch a sample.
7. Every Mouse Over loads the information into the tooltip control just in-time (on demand) and I am relatively sure either every Mouse Over do a round trip to the server to get the data which is also not OK and not performant. 
8. Or even if the thought behind point 7 isn't the case and the application would load everything ahead of time, we are occupying the local RAM with information the user isn't and can't use properly and this again isn't OK either.

**What I would do**: Just turn the tooltip for SQL Command Text OFF. Hovering over the text should simply not show any tooltip at all. Users who need the information in the grid column field must click the hyperlink and load the content in Code Viewer ANYWAY :D

**Comment by EsQueEl-Fella** [comment] 2023-11-15 12:24
Here one sample for the vertical growth ! The frame doesn't even fit the 27 inch screen and spans over. I was lucky (or unlucky :D) that the application didn't freeze this time.

![grafik](https://github.com/trimble-oss/dba-dash/assets/40255900/986189e0-32b5-495f-b8d1-d35c04e8eb20)

**Comment by DavidWiseman** [comment] 2023-11-15 16:41
The tooltips are default behaviour for the grid control in .NET rather than something that was added intentionally.  The tooltips don't result in any additional round trips to the server.  The data is loaded in the grid and the tooltip is automatic.  It also just passes the text to the code viewer without querying the server again.

The tooltips should remain visible as long as the mouse is hovered over cell in the grid.  

I find the tooltips useful on occasion as they allow you to quickly see what the query is in situations where that's not obvious from the smaller amount of text shown in the cell.  For larger queries you do get a tooltip that is too large - it would definitely be better to have it truncated.  That does mean some work to override the default behaviour which is provided automatically.  

I also have some large queries where the tooltips are not ideal - but I've never experienced any crashes or freezes because of the tooltips.  I'm guessing it might cause problems if the text is really huge and it could be dependant on the amount of RAM available etc.  

I'll consider options for improving this in future releases.

**Comment by EsQueEl-Fella** [comment] 2023-11-16 10:49
Hi, 

Thanks for Information above. I am aware of most of the points above. And that wasn't / isn't my point. Usabilily is my point. 

Anyways, if you decide to truncate the content to a resonable level, then it's also a good solution. Looking forward to that.

As of catching the case when application freeze, I will send you an image the next time this happens. It does happen when really huge content are being loaded and as I am not aware what is behind the Link I can't send you a sample now, I need to wait and search until I catch one sample.

**Comment by DavidWiseman** [comment] 2023-11-21 20:39
I can re-produce this issue.

Reproduction steps:
Generate a large string.  10K comma-separated INTs from DBA Dash repository DB will do it.
```sql
SELECT
(SELECT TOP(10000) CONCAT(',',WaitTYpeID )
FROM dbo.Waits 
FOR XML PATH(''),TYPE).value('.','NVARCHAR(MAX)')
```
Run a WAITFOR DELAY command with the IDs in a comment. e.g.
```
WAITFOR DELAY '00:01:00' /* 403,405,408,........{10K items}*/
```
The query text was 38K for this test.  I haven't experimented with different sizes to see what the threshold is.

This might be similar to an entity framework query passing a very long list of items etc.

The WAITFOR command ensures the query will run long enough to be captured by running query snapshots & slow queries.

I can confirm that this either causes an application crash or severe performance issues.  What's interesting is if you add a newline character after each comma the tooltip displays immediately with no issues.  The size of the text is exactly the same.  So the important thing to reproduce the issue is not the size of the text but the width.  A gigantic stored procedure is probably fine - an ORM query passing in a lot of items isn't.

I have a neat way to truncate the tooltip text for all the grids in the app.  Not sure what I'll truncate to but it currently works with 1K chars.  This seems like a reasonable length.  It can still result in tooltips that are too wide/tall but will usually result in a reasonably sized tooltip.  Even if the text is very wide - 1000 chars fixes the crashing and slow performance issues.

For any users affected by this, it would definitely be an annoying problem.  Fix coming soon.

**Comment by DavidWiseman** [comment] 2023-11-21 21:20
I'm going to default to 1000 chars.  I expect most people won't need to change this, but it will be configurable if needed.  This would totally disable cell tooltips.

```
DELETE dbo.Settings WHERE SettingName='GUICellToolTipMaxLength'
INSERT INTO dbo.Settings(SettingName,SettingValue)
VALUES('GUICellToolTipMaxLength',0)
```

For wide text - 
1000 works great for me.  2000 has a slight delay (It's OK but not worth having a performance hit).  The delay increases as you go up.

**Comment by DavidWiseman** [comment] 2023-12-04 09:06
This issue is fixed now in the new version. 🎉

**Closed by DavidWiseman** 2023-12-04 09:06 UTC
Labels: DBA Dash GUI, Completed
